travis:
  secure:
    BINSTAR_TOKEN: iPH5iW/hnR2KXo1neqHpaSbLNbJzCHOK0Khb3UobwCkPF98nSx+Gc0JJ5RxFJW6j2lQmNO/pMKX0Bksew2wX/IORPyZiGR7VtHnbBje+ywzCDP5VVAd1eC/XbFkiY58QWI7zijJlIds0WPwE1N/apjn5Wv3KOKtQ0013Ij7PztCs6+M/vaKZiZvJGqUnjFG4SMASmM6vDPxKIMLNpcCP97PiedClkKw0NU7xoH9hqSwLEotj1VbpXUqjHcQ2v0vHI+tvFDBWfrKa0+SPbYLHmiKU/ZoEFhl1UusQlq9SSAUJUfj1Ilokpm/4hw2OSqkCWHteLrSNdC0/Uw2vvrY3FGGatQiL+MVCE6kRGdvHNw+GgQJT2LHcH2zZb+NjzGwoU9XJmvK+LwxUahEhEjO75ihnGPIWrf/1f/RN3EdFK6NYz49/mnW1PTxx7MK61cMfVOgJ+FuqnxnGpheWEIX1K7w6WyXZ5t3aCj/lSG/rMURL6TGszTa5ct6ZJAuDPv6KNUUbuplpU2nzdrun+aFKlz6LaQWCVzaY5j7CI6ISVBOn4if7ZZsAF7bAGMTHABeghCY1cXGRPnqwzDxVzNOIri48/2paPg5M4YX0+f54OsJi9+mbuikYZPVe5JNOxVLo3wyTqWQ/c4johfDEEQ5G8ZfMGS14LP71w5O2+gDK7kM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
